#!/bin/bash

NAME="django-crypto-repo"
DIR=/srv/CIP/django-crypto-repo
USER=uconsumer
GROUP=nogroup
WORKERS=3
BIND=unix:/srv/CIP/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=crypto_repo.settings
DJANGO_WSGI_MODULE=crypto_repo.wsgi
LOG_LEVEL=error

cd $DIR
source ../venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-