# Generated by Django 2.0.3 on 2018-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdax_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='sequence',
            field=models.BigIntegerField(),
        ),
    ]
