# Generated by Django 2.0.3 on 2018-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdax_app', '0002_auto_20180321_1628'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticker',
            name='gdax_app_ti_time_fe3e23_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['rate'], name='gdax_app_or_rate_a8cbac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['quantity'], name='gdax_app_or_quantit_cd1d23_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['time'], name='gdax_app_or_time_1f1439_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['best_bid'], name='gdax_app_ti_best_bi_e26cac_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['best_ask'], name='gdax_app_ti_best_as_06dba0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['price'], name='gdax_app_ti_price_ef054c_idx'),
        ),
    ]
