# Generated by Django 2.0.3 on 2018-03-16 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('verbose', models.CharField(max_length=100, null=True)),
                ('tkr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('base_currency', models.CharField(max_length=10)),
                ('min_trade_size', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('abstractorderbook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.AbstractOrderBook')),
            ],
            bases=('common.abstractorderbook',),
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_btc', models.FloatField(null=True)),
                ('ask_btc', models.FloatField(null=True)),
                ('bid_usd', models.FloatField(null=True)),
                ('ask_usd', models.FloatField(null=True)),
                ('bid_eur', models.FloatField(null=True)),
                ('ask_eur', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['time'], name='bittrex_tic_time_345c40_idx'),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bittrex.Coin'),
        ),
    ]
