# Generated by Django 2.0.3 on 2018-03-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(max_length=100, null=True)),
                ('tkr', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('min_trade_size', models.FloatField()),
                ('ice_berg_allowed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.BooleanField()),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('time', models.DateTimeField()),
                ('last_updated', models.IntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance.Market')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price_change', models.FloatField()),
                ('w_a_price', models.FloatField()),
                ('prev_close_price', models.FloatField()),
                ('last_price', models.FloatField()),
                ('bid_price', models.FloatField()),
                ('ask_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('trade_count', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance.Market')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('tkr', 'quote')},
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['time'], name='binance_tic_time_876ffd_idx'),
        ),
    ]
