# Generated by Django 2.0.3 on 2018-03-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(max_length=100, null=True)),
                ('tkr', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('min_trade_size', models.FloatField()),
                ('ice_berg_allowed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.BooleanField()),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('time', models.DateTimeField()),
                ('last_updated', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_btc', models.FloatField(null=True)),
                ('ask_btc', models.FloatField(null=True)),
                ('bid_usd', models.FloatField(null=True)),
                ('ask_usd', models.FloatField(null=True)),
                ('bid_eur', models.FloatField(null=True)),
                ('ask_eur', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['time'], name='binance_tic_time_876ffd_idx'),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance.Market'),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('tkr', 'quote')},
        ),
    ]
