# Generated by Django 2.0.3 on 2018-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfinex_app', '0002_auto_20180321_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticker',
            name='bitfinex_ap_time_afcd9a_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['time'], name='bitfinex_ap_time_1ee875_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_updated'], name='bitfinex_ap_last_up_e20a99_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['time'], name='bitfinex_ap_time_545fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['ask'], name='bitfinex_ap_ask_995771_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['bid'], name='bitfinex_ap_bid_042d84_idx'),
        ),
    ]
