# Generated by Django 2.0.3 on 2018-03-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bittrex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('tkr', 'base_currency')},
        ),
    ]
