# Generated by Django 2.0.3 on 2018-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bittrex_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticker',
            name='bittrex_app_time_da04a9_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['rate'], name='bittrex_app_rate_2fbf95_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['quantity'], name='bittrex_app_quantit_a8dd50_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['time'], name='bittrex_app_time_a770f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['bid'], name='bittrex_app_bid_4909d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['ask'], name='bittrex_app_ask_f49495_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['last'], name='bittrex_app_last_877942_idx'),
        ),
    ]
