# Generated by Django 2.0.3 on 2018-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0002_auto_20180321_1628'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticker',
            name='binance_app_time_e6aa7f_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['rate'], name='binance_app_rate_ae23dd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['quantity'], name='binance_app_quantit_d132bd_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['time'], name='binance_app_time_963f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['last_price'], name='binance_app_last_pr_62ba5f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['bid_price'], name='binance_app_bid_pri_18fd56_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['ask_price'], name='binance_app_ask_pri_9009da_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['volume'], name='binance_app_volume_a04577_idx'),
        ),
    ]
